### ISSUE TITLE
As a project member, I want to see the costs of my project so that I can predict the final amounts

### ISSUE THREAD

**Issue by yjmrobert** [ssc-sp/datahub-portal#121]
## Tasks

- [x] #352
- [x] #358
- [ ] #382
- [ ] #383

## Supporting Documentation

Placement mockup
![image](https://user-images.githubusercontent.com/43834308/202261284-0508c046-4dd3-4f7e-ac5d-f67d718dd360.png)

Card mockups
![image](https://user-images.githubusercontent.com/43834308/202261332-9ef99783-5df0-4b2a-a839-a4f8a4491093.png)

**Comment by ErikApption** [comment]
Going to close this one. The calculators are out of scope for now.
