### ISSUE TITLE
Azure Postgresql wasn't added

### ISSUE THREAD

**Issue by gwajnberg** [ssc-sp/datahub-portal#1219]
### Bug type

DataHub Portal

### What happened?

I submitted the metadata with success, then tried to add a Azure Postresql to my workspace last Friday (June 28th). It is being provisioned since then with no luck until today (July 2nd).
![printscreenWS](https://github.com/ssc-sp/datahub-portal/assets/1334454/ea98a232-c064-4dc9-91c7-56697871b2ce)

### Expected behavior

Expected that Azure Postgresql instance being available after these 4 days clicking the button to add to workspace.

### Reproduction steps

1. Saved the metadata
2. Clicked in the tool box in the side bar
3. Clicked in "Add to workspace"  under Azure Postgres option
...

### What browsers are you seeing the problem on?

Firefox, Chrome, Microsoft Edge

### On what operating system are you experiencing the issue?

Windows

### Code of Conduct

- [X] I agree that none of the information provided is confidential.

**Comment by Sean-Stilwell** [comment]
I've completed the provisioning, it looks like the database is available now.

**Comment by gwajnberg** [comment]
Thanks!
________________________________
