### ISSUE TITLE
Identify E2E testing options (pros & cons)

### ISSUE THREAD

**Issue by yjmrobert** [ssc-sp/datahub-portal#214]

**Comment by davidreneuw** [comment]
Here are a list of options of frameworks to use for E2E testing, specifically using Snapshot tests.

- [**Playwright .NET**](https://playwright.dev/dotnet/docs/intro):
➕ Has strong support for .NET framework and auto-test generators and has great documentation + good github CI
➖
- [**Jest**](https://jestjs.io/docs/snapshot-testing):
➕ Has good documentation, provides solid github CI
➖ It's component-wise snapshotting is limited to JS frameworks
-  [**Cypress**](https://docs.cypress.io/guides/overview/why-cypress):
➕ Very similar to Jest, good documentation and good github CI
➖ Component-wise testing also limited to JS frameworks
