### ISSUE TITLE
Breadcrumbs are inconsistent and do not leverage the page title

### ISSUE THREAD

**Issue by ErikApption** [ssc-sp/datahub-portal#217]
**Describe the bug**
Breadcrumbs seem to leverage the URL path instead of the Page Title. The name in breadcrumb is often different from page title and changes depending on context. This breaks localization in several use cases.

![image](https://user-images.githubusercontent.com/3179656/204909483-e7b0ce1f-e66e-4771-ae2e-acefb7560223.png)

**Comment by yjmrobert** [comment]
I'll take this one inside of #310
