### ISSUE TITLE
Provide a way for developer to get the appsettings without having to contact someone

### ISSUE THREAD

**Issue by yjmrobert** [ssc-sp/datahub-portal#220]
Need to go through the code base and determine all of the used configuration values (ie, check for `using IConfiguration`'s) so that the appsettings can be trimmed down to required values.

These keys (not the secret values) need to be documented in the Wiki in table form.

Next steps involve using [AKV as a configuration provider in ASP.NET core](https://learn.microsoft.com/en-us/aspnet/core/security/key-vault-configuration?view=aspnetcore-7.0) and writing a script to hydrate the AKV using `az cli`

**Comment by yjmrobert** [comment]
Hey @MatteoGisondi there might also be a use case around creating/recycling service principals. Meeting with cloud team next week to go over the possible processes

**Comment by ErikApption** [comment]
need to find some guidance on this - this can't be an isolated issue...

**Comment by yjmrobert** [comment]
I've resolved this, the mechanisms are in our ADO wiki
