### ISSUE TITLE
Welcome Page Banners not displaying correctly

### ISSUE THREAD

**Issue by yjmrobert** [ssc-sp/datahub-portal#225]
**Describe the bug**
The new wiki structure does not line up with the DHPageAlerts and needs to be updated and it's not displaying the banners/alerts.

**To Reproduce**
1. Go to any page for the first time

**Expected behavior**
To see the page banner with description pulled from the wiki

**Comment by yjmrobert** [comment]
hey @iroelperez, could you take a look at this one?

**Comment by iroelperez** [comment]
Sure, I'll take a look.
