### ISSUE TITLE
Improve Terraform update efficiency

### ISSUE THREAD

**Issue by simon-wang-gc** [ssc-sp/datahub-portal#253]
- [ ] Ensure the Terraform apply process does not unduely recreate resoruce (delete/create) and cause downtime
- [ ] Ensure the Terraform apply process does not unduely take too much time

**Comment by yjmrobert** [comment]
Sent you a notice here with my timings from last week https://github.com/ssc-sp/datahub-portal/issues/206#issuecomment-1376609940

I found that it will recreate Databricks users when updating the list - so there's a short window (2~3m) where access won't exist after adding or removing users on a project

**Comment by yjmrobert** [comment]
@simon-wang-gc is this good enough? I felt like it was running smoothly enough when modifying

**Comment by simon-wang-gc** [comment]
I would like to look at why so many destroys when running update
