### ISSUE TITLE
Pipelines fail or output error when terraform has a problem

### ISSUE THREAD

**Issue by yjmrobert** [ssc-sp/datahub-portal#255]
Pipelines should pass or fail based on the terraform result

**Comment by yjmrobert** [comment]
@simon-wang-gc are you able to take this one? Low priority for now but it would be nice to record the pass/fail somewhere eventually

**Comment by simon-wang-gc** [comment]
Sure I will look into this and advise.

**Comment by simon-wang-gc** [comment]
I have updated the pipeline such that the Terraform apply task would fail if any error.
