### ISSUE TITLE
Create a pipeline to run when a datahub-docs main PR is merged

### ISSUE THREAD

**Issue by iroelperez** [ssc-sp/datahub-portal#264]
**Is your feature request related to a problem? Please describe.**
Right now, we have to manually run the sync tool and this is a bit annoying.  :)

**Describe the solution you'd like**

The pipeline should do the following:

- checkout the datahub-docs (e.g. in folder "docs")
- checkout the datahub-portal 
- cd to folder ./Portal/utils/SyncDocs
- set the DeepL key in and env var 'DEEPL_KEY' (contact @iroelperez for a temporary key) 
- run: dotnet run _docs_folder_path_
- commit and push the datahub-docs repo

**Describe alternatives you've considered**
There is probably a better solution involving a PR, but this is what manually do today to sync the docs.

**Comment by iroelperez** [comment]
@ErikApption suggested the PS script to look like:

I do think the ps part will be very simple... the script would only:

- pull the most recent docs repo
- load the deepl key from secret file into env variable... $env:DEEPL_KEY=Get-Content "deepl.key"
- run the translation tool - would need some path config but something like dotnet run deepltranslate.csproj - I think the tricky - part here is to figure out the directory structure
- push all the directory. git add (_edited_)
- push the commit to the repo git commit -m "deepl translation from 2022-01-11"

**Comment by simon-wang-gc** [comment]
Yes that sounds very do-able. I am looking into it

**Comment by simon-wang-gc** [comment]
The pipeline has been created. Future work will be tracked as separate issues
