### ISSUE TITLE
Duplicate resource requests

### ISSUE THREAD

**Issue by ErikApption** [ssc-sp/datahub-portal#332]
**Describe the bug**
Not sure if we have a safety to prevent duplicate resource requests
![image](https://user-images.githubusercontent.com/3179656/216139353-caa43c4b-06b3-4641-b47a-70b7f68c0c56.png)

**Comment by yjmrobert** [comment]
We don't but it does do anything in the Resource Provisioner side (no changes to commit detected). 

Should we block that at the portal side?

**Comment by yjmrobert** [comment]
Resolved with latests changes
