### ISSUE TITLE
Extract NRC consumption data for development

### ISSUE THREAD

**Issue by yjmrobert** [ssc-sp/datahub-portal#344]
Great dataset of actual use case with large numbers that can be leveraged to help develop the costing features. Need to extract it with as much detail as possible.

CSV? Database Table?

**Comment by yjmrobert** [comment]
Need to bump this in priority as we don't know for how long we'll be able to capture this in the environment

**Comment by yjmrobert** [comment]
cc @simon-wang-gc could we manually create a project and import the existing resources into their terraform project?

**Comment by iroelperez** [comment]
I'll look into this next.

**Comment by yjmrobert** [comment]
@iroelperez I think you got this working, good to close?
