### ISSUE TITLE
Add project storage alert

### ISSUE THREAD

**Issue by simon-wang-gc** [ssc-sp/datahub-portal#347]
Add notification to project owners if the storage usage reaches certain threhold

**Comment by yjmrobert** [comment]
@simon-wang-gc is this for the Terraform fail safe?

I believe @iroelperez has completed a nightly check on the size

**Comment by simon-wang-gc** [comment]
Azure has built-in metric on used capacity which could also trigger notifications

**Comment by yjmrobert** [comment]
Closing as @iroelperez has completed it already
