### ISSUE TITLE
Hard stop resource group usage after much higher cost exceeded limit

### ISSUE THREAD

**Issue by simon-wang-gc** [ssc-sp/datahub-portal#349]
- [x] Develop an automation runbook
- [x] Add action group
- [x] Develop runbook script using powershell to disable CMK and lock resource group

**Comment by simon-wang-gc** [comment]
There seems to be a bug as Terraform does not associate action groups with budget alerts

**Comment by yjmrobert** [comment]
@simon-wang-gc were you able to resolve the hard stop with the key fail safe?

**Comment by simon-wang-gc** [comment]
Need to adjust the cost accumulation period to 6 month based on the latest discussion

**Comment by simon-wang-gc** [comment]
to be tested

**Comment by simon-wang-gc** [comment]
Complete
