### ISSUE TITLE
Reliability improvement for project resource provisioning

### ISSUE THREAD

**Issue by simon-wang-gc** [ssc-sp/datahub-portal#361]
We need to repeatedly test the resource provisioning in project modules (i.e. /sample-project) to make sure it runs reliably because the sample project may fail once in a while. This task cannot be easily automated because the ADO pipeline would timeout based on the current settings. There may be other potential automation approach (e.g. using a always-on VM)

**Comment by yjmrobert** [comment]
Added to #215 as a future task

> Create health check for resource deployment

Closing this as it's moved to the backlog
