### ISSUE TITLE
Investigate the use of user-managed identity in datahub infra

### ISSUE THREAD

**Issue by simon-wang-gc** [ssc-sp/datahub-portal#400]
For some Azure resources, using user managed identity (UMI) can reduce permission scope thus enhance security.

**Comment by simon-wang-gc** [comment]
https://learn.microsoft.com/en-us/azure/azure-sql/database/authentication-aad-service-principal?view=azuresql
https://learn.microsoft.com/en-us/azure/azure-sql/database/authentication-azure-ad-user-assigned-managed-identity?view=azuresql

**Comment by ErikApption** [comment]
I think we should look at which resources this would be the best applied. Once we enable user-managed identities, it will make some testing and development more complicated, like functions. @simon-wang-gc I think we are already using managed identities for all database connections, correct?
