### ISSUE TITLE
Creating a workspace with a custom acronym doesn't use the custom acronym

### ISSUE THREAD

**Issue by yjmrobert** [ssc-sp/datahub-portal#410]
I manually entered `DHPGLIST` but was given `DAAD`

![image](https://user-images.githubusercontent.com/43834308/221285216-6c73480c-d6f8-4e36-b29b-01fe6e6e61e4.png)

**Comment by ErikApption** [comment]
Was looking at that one and it looks like the auto fill behavior was changed.
