### ISSUE TITLE
Platform status page for end users

### ISSUE THREAD

**Issue by ErikApption** [ssc-sp/datahub-portal#450]
Create a page available for users and administrators to validate overall platform status

- My workspace
  - Status of my Databricks instance: could be as simple as checking if the url in our DB points to a legit instance
  - Status of my Storage: same thing as above
- System
  - Status of system queues
- Devops
  - Status of pipelines: could be something related to last execution - e.g. raise a flag if last execution is older than 24hrs

**Comment by yjmrobert** [comment]
Also allow datahub admins to re-run any failed resource runs
