### ISSUE TITLE
Create setup page for first user

### ISSUE THREAD

**Issue by yjmrobert** [ssc-sp/datahub-portal#475]
Need a way for the first user to become an administrator on the site. Current process is a manual script against the database, this needs to be reworked into a proper setup page.

## Tasks
- [ ] Create a setup page that is displayed when the `DHPGLIST` project does not exist
- [ ] Have first time user enter a code from the logs that can be entered to inherit admin of `DHPGLIST`

**Comment by ErikApption** [comment]
To add a bit more security: 
1. when the app starts, if there is nothing in the project list, we generate an installation code in the logs
2. the setup page asks for the installation code - this way nobody can hijack the new setup page without having access to the backend
