### ISSUE TITLE
Error when adding new application

### ISSUE THREAD

**Issue by Lorb74** [ssc-sp/datahub-portal#492]
Under Tools > Onboarding Form > Applications, clicking on "Add New" throws the following error:

Something went wrong
TECHNICAL DETAILS
An application error has occurred on the DataHub server. The error has been recorded with Correlation ID 4dee9e99-42ac-4e07-b669-2daab3e1aa67. To avoid network issues, if you are currently on the VPN, please try to disconnect the VPN and retry your actions.

AppInsights Query
exceptions
| where customDimensions.correlationId == '4dee9e99-42ac-4e07-b669-2daab3e1aa67'
Message
Request index for Client_Sector is 0 but list has 0 values
Stack Trace
   at Elemental.Components.AeDropdownPropertyInput`1.UpdateOptions()
   at Elemental.Components.AeDropdownPropertyInput`1.OnInitializedAsync()
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()

**Comment by yjmrobert** [comment]
@Lorb74 I don't know if you want to tackle this one yourself? That shouldn't be accessible to users

**Comment by Lorb74** [comment]
@yjmrobert , what's the process for the bug? Once resolved, is it sent back to me for validation

**Comment by yjmrobert** [comment]
> @yjmrobert , what's the process for the bug? Once resolved, is it sent back to me for validation

We've been validating them off each other via Pull Request reviews. If you'd like I can ping you before we close it?

**Comment by ErikApption** [comment]
closing this one since tools is not visible
