### ISSUE TITLE
Welcome email notification for collaborators when added to workspace

### ISSUE THREAD

**Issue by ErikApption** [ssc-sp/datahub-portal#505]
- [x] Disable AAD default email from the CreateGraphUser function
- [x] Send `Welcome to DataHub` email when a user is registered in the CreateGraphUser function
- [x] Send an `Added to Project` email when a collaborator is added

**Comment by iroelperez** [comment]
This issue is completed but there is still a pending possible change: sending an email when the role is assigned to a user.

**Comment by ErikApption** [comment]
closing this one - the role would be a feature not a priority item
