### ISSUE TITLE
Opening costs page redirects to home

### ISSUE THREAD

**Issue by yjmrobert** [ssc-sp/datahub-portal#529]
When a new project is made and you click on costs it redirects to home page. Should stay within the project and show that no costs have been incurred yet

**Comment by ErikApption** [comment]
I would hide the costing - no need to add more wording

**Comment by ErikApption** [comment]
also related is https://github.com/ssc-sp/datahub-portal/issues/507 - if we don't have up-to-date data - we should hide the costing or put an error message

**Comment by iroelperez** [comment]
Project cost chip will be disabled until there is a credit report in the db
