### ISSUE TITLE
Workspace will show error message if permissions are changed during session

### ISSUE THREAD

**Issue by yjmrobert** [ssc-sp/datahub-portal#531]
When a user is added to a workspace but before they refresh their claims - they can navigate to the workspace page and see the request access button.

When a user is detected that they are in a project page and are one of the project users but do not have the claims. Trigger a refresh

**Comment by ErikApption** [comment]
This sounds complicated, especially detecting changes in permissions - I'm thinking adding a section in the docs for common issues.

**Comment by ErikApption** [comment]
We could add also some text in the access denied: "If you have been granted recently access - please reload the website using F5"

**Comment by ErikApption** [comment]
![image](https://user-images.githubusercontent.com/3179656/225646371-d0753915-434f-4f42-a8f7-51449d9aab88.png)

**Comment by ErikApption** [comment]
Text has been updated with link to refresh page. We assume this should be sufficient for now
