### ISSUE TITLE
Create badges for achievements

### ISSUE THREAD

**Issue by ErikApption** [ssc-sp/datahub-portal#534]
Provide something tangible for users to earn badges. Would be nice to have somekind of icon framework where we overlay badges

**Comment by ErikApption** [comment]
I'm thinking we do badges for
- platinum
- gold
- silver
- bronze
based on number of achievements. Badge is displayed top right near the user name

**Comment by yjmrobert** [comment]
Another idea that was recently added was profile pictures and profile backgrounds

**Comment by yjmrobert** [comment]
covered in #662
