### ISSUE TITLE
As a workspace Lead/Admin but not a Datahub Admin, I am unable to manage workspace members 

### ISSUE THREAD

**Issue by nicksalt** [ssc-sp/datahub-portal#541]
Steps to reproduce:
1. Access the DataHub portal from a non-DataHub admin account
2. Access a workspace you are an Admin or Workspace Lead of
3. `Manage Members` button is missing from the list of Admins
4. Trying to directly access `w/{PROJECT_ACRONYM}/members` does not load the workspace members table (permissions fail)

**Comment by nicksalt** [comment]
Related to role usage in the project management access.

**Comment by yjmrobert** [comment]
closed as it's fixed
