### ISSUE TITLE
"View As Visitor" switch in UI does nothing 

### ISSUE THREAD

**Issue by nicksalt** [ssc-sp/datahub-portal#547]
![image](https://user-images.githubusercontent.com/15818609/225726679-63f0a142-2a8f-48a8-9cca-fd5ab9a5a71f.png)
Hitting this switch in the TopBar popover currently does nothing. It should remove all roles.

**Comment by yjmrobert** [comment]
Moving to backlog

**Comment by ErikApption** [comment]
Visitor view is the concept that someone is in the portal but doesn't have any workspace. The objective is to hide certain elements to simplify the navigation. We don't have visitors rights now so this doesn't do anything so going to close the issue.
