### ISSUE TITLE
Engagement Model for new Client

### ISSUE THREAD

**Issue by ErikApption** [ssc-sp/datahub-portal#57]

**Comment by Lynnehunks** [comment]
Initial draft engagement ('onboarding') approach -- see 
https://163gc.sharepoint.com/:p:/r/sites/ScienceProgram/_layouts/15/Doc.aspx?sourcedoc=%7Ba3c46e89-d245-4de9-aee4-dea3e5a334dd%7D&action=edit&uid=%7BA3C46E89-D245-4DE9-AEE4-DEA3E5A334DD%7D&ListItemId=12480&ListId=%7B1D050BC3-FEAC-46DF-83FA-9709AC88DF90%7D&odsp=1&env=prod
