### ISSUE TITLE
Missing translation

### ISSUE THREAD

**Issue by yjmrobert** [ssc-sp/datahub-portal#577]
### Bug type

DataHub Portal

### What happened?

![image](https://user-images.githubusercontent.com/43834308/226487968-5276f519-e883-46f1-8814-cb056bd6d29b.png)
There is no translation for "No recent data"

### Expected behavior

It should say `Aucune donnée récente`

### Reproduction steps

1. Navigate to a workspace for which you can see the cost but hasn't incurred any yet (create a new one)

### What browsers are you seeing the problem on?

Chrome

### On what operating system are you experiencing the issue?

Windows

### Code of Conduct

- [X] I agree that none of the information provided is confidential.

**Comment by ErikApption** [comment]
resolved in hot fix
