### ISSUE TITLE
Missing Translation for admins

### ISSUE THREAD

**Issue by yjmrobert** [ssc-sp/datahub-portal#580]
### Bug type

DataHub Portal

### What happened?

![image](https://user-images.githubusercontent.com/43834308/226622486-e3a78f9f-7cd1-4950-8c37-88055d4a9b63.png)
 

### Expected behavior

Needs translating to french

### Reproduction steps

1. Open portal as datahub admin
2. Switch to FR
3. Open a workspace

### What browsers are you seeing the problem on?

Chrome

### On what operating system are you experiencing the issue?

Windows

### Code of Conduct

- [X] I agree that none of the information provided is confidential.

**Comment by ErikApption** [comment]
fixed in PR
