### ISSUE TITLE
Missing Translation

### ISSUE THREAD

**Issue by yjmrobert** [ssc-sp/datahub-portal#593]
### Bug type

DataHub Portal

### What happened?

![image](https://user-images.githubusercontent.com/43834308/227254982-3ad5cc28-6038-4b70-bb45-b49939e2a3ad.png)

### Expected behavior

Should be in french

### Reproduction steps

1. Navigate to file explorer
2. Click AzCopy tab
3. Click on Generate Token

### What browsers are you seeing the problem on?

Chrome

### On what operating system are you experiencing the issue?

Windows

### Code of Conduct

- [X] I agree that none of the information provided is confidential.

**Comment by ErikApption** [comment]
pushed hotfix to dev branch
