### ISSUE TITLE
Redirect after login to entered url

### ISSUE THREAD

**Issue by yjmrobert** [ssc-sp/datahub-portal#619]
### Bug type

DataHub Portal

### What happened?

Some users are being redirected back to the home page instead of the URL they entered into the address bar 

### Expected behavior

The page should open to the url entered in the address bar

### Reproduction steps

1. Open incognito
2. Enter a link that's not `/home` or `/`
3. Get redirected to `/home` after login

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge

### On what operating system are you experiencing the issue?

Windows

### Code of Conduct

- [X] I agree that none of the information provided is confidential.

**Comment by ErikApption** [comment]
isn't this something out of our scope? I believe the redirect URL is handled by the login page and is passed by the OIDC framework.

**Comment by yjmrobert** [comment]
Not exactly, our main layout redirects to /login which redirects back to the base uri after OIDC auth.

**Comment by ErikApption** [comment]
isn't the original URL was passed as parameter to the login? There must be a standard pattern to implement that
