### ISSUE TITLE
French docs not auto-translating "FSDH" and "Federal Science DataHub"

### ISSUE THREAD

**Issue by Lynnehunks** [ssc-sp/datahub-portal#620]
### Bug type

DataHub Portal

### What happened?

French github docs not updated after changes made to English docs.

And -- auto translate did not translate FSDH and Federal Science DataHub in any of the French docs.

### Expected behavior

French docs, including the sidebar, should be updated as soon as English files are updated.

AND

We need auto-translate to always translate as follows:

FSDH > DHSF   and    Federal Science DataHub > DataHub scientifique fédéral 

### Reproduction steps

Changed profile to french and docs are not synced to english.

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge

### On what operating system are you experiencing the issue?

Windows

### Code of Conduct

- [X] I agree that none of the information provided is confidential.

**Comment by Lynnehunks** [comment]
There are 2 issues here. Should I split this into 2?

ISSUE 1 - French does not match English
ISSUE 2 - when auto translate runs it does not change FSDH to DHSF or Federal Science DataHub to DataHub scientifique fédéral

**Comment by Lynnehunks** [comment]
![image](https://user-images.githubusercontent.com/99416857/228854008-5b6e4f47-4dae-4953-a687-e6a268f0e21e.png)

**Comment by Lynnehunks** [comment]
![image](https://user-images.githubusercontent.com/99416857/228854193-bd235d01-3dab-4d7e-a7a5-67173f587156.png)

**Comment by Lynnehunks** [comment]
The sidebars don't match.

The content of the 'tiles' (md docs in github) do not match, where changes have been made in English

**Comment by Lynnehunks** [comment]
![image](https://user-images.githubusercontent.com/99416857/228855230-b9375c5d-7a43-44a1-8b94-28e8c24e158b.png)

The French acronym for FSDH is DHSF

**Comment by yjmrobert** [comment]
I'm going to split this up into two issues, see #621 for the pipeline related issue

**Comment by iroelperez** [comment]
The glossary has been added and the changes are in the SyncDocs tool already. Can we close this one?

**Comment by iroelperez** [comment]
I ran the SyncDocs and it is overriding French files that were manually edited 'cause the "draft" setting was "true" still. I would like to review these files with @Lynnehunks then I'll update the docs.
