### ISSUE TITLE
French github docs not updated after changes made to English docs

### ISSUE THREAD

**Issue by yjmrobert** [ssc-sp/datahub-portal#621]
### Bug type

Other

### What happened?

French github docs not updated after changes made to English docs.

### Expected behavior

It should trigger a pipeline to update the french contents

### Reproduction steps

1. Edit english docs
2. View french docs

### What browsers are you seeing the problem on?

Chrome

### On what operating system are you experiencing the issue?

Windows

### Code of Conduct

- [X] I agree that none of the information provided is confidential.

**Comment by ErikApption** [comment]
Needs production key
