### ISSUE TITLE
Add auditing to workspace member modifications

### ISSUE THREAD

**Issue by yjmrobert** [ssc-sp/datahub-portal#628]
Taken from https://github.com/ssc-sp/datahub-portal/pull/605#pullrequestreview-1359577984

Refactor the user management in a workspace to use a command pattern and save the commands in the database for auditing.

**Comment by ErikApption** [comment]
- add member/remove member/invite
- change role
- track changes in log analytics
- changes should already be tracked through savechange tracking - needs confirmation
