### ISSUE TITLE
Metadata Auto translate not working

### ISSUE THREAD

**Issue by yjmrobert** [ssc-sp/datahub-portal#644]
### Bug type

DataHub Portal

### What happened?

I can't click on it to translate

### Expected behavior

It should translate

### Reproduction steps

1.
2.
3.
...

### What browsers are you seeing the problem on?

Chrome

### On what operating system are you experiencing the issue?

Windows

### Code of Conduct

- [X] I agree that none of the information provided is confidential.

**Comment by ErikApption** [comment]
We need to get a production key for translation

**Comment by iroelperez** [comment]
Can I close this one?
