### ISSUE TITLE
Email notifications for updated files

### ISSUE THREAD

**Issue by ErikApption** [ssc-sp/datahub-portal#651]
I'm certain we had a version of this as a function - but  the idea is to send an email to all collaborators of a project on a daily (weekly?) basis when the files have been updated in the storage account.

**Comment by yjmrobert** [comment]
We did, I've received those emails before

**Comment by yjmrobert** [comment]
![image](https://user-images.githubusercontent.com/43834308/231165415-e809aa4e-c6f3-4d38-8685-642ef7b7f477.png)

**Comment by yjmrobert** [comment]
Is this something we want to add?
