### ISSUE TITLE
Investigate R support in Databricks

### ISSUE THREAD

**Issue by ErikApption** [ssc-sp/datahub-portal#686]
CanSIS says R is not working in their cluster

**Comment by simon-wang-gc** [comment]
The main clusters all have R support. Any other clusters created before the policy update need to be recreated (not many)

**Comment by simon-wang-gc** [comment]
Technically we could but those clusters were created by users and not managed by Terraform

**Comment by ErikApption** [comment]
So in terms of comms - sounds like we should say "If you have created manually a cluster in Databricks, it will need to be deleted and re-created. Contact us if you need any help on that procedure."

**Comment by simon-wang-gc** [comment]
If you have manually created manually your own clusters in Databricks **before April 17, 2023 and require R language support**, they will need to be deleted and re-created. Contact us if you need any help on that procedure.
