### ISSUE TITLE
Resourcing Service for Datahub

### ISSUE THREAD

**Issue by yjmrobert** [ssc-sp/datahub-portal#69]
Create service in Datahub to call the Resourcing Provisioner endpoints 

- [ ] Request resource run
  - [ ] New project template
  - [ ] Azure blob storage
  - [ ] Azure Databricks workspace
- [ ] Get project resources
- [ ] Get pull requests

**Comment by nicksalt** [comment]
@yjmrobert , I think this one is safe to close?

**Comment by yjmrobert** [comment]
Yeah, I'm just letting stale bot do it though

**Comment by yjmrobert** [comment]
Although we just resurrected it... Closing it lok
