### ISSUE TITLE
Open demo workspace/notebooks for all users

### ISSUE THREAD

**Issue by ErikApption** [ssc-sp/datahub-portal#692]
Main objective is for all users to access our demo notebooks so that they can copy/paste and run our sample code.
Wondering what options we have... I'm thinking
- [x] #698 
- [ ] Enable a public flag on a workspace to open it to all users
- [ ] Should we use a public group in databricks to allow everybody?
- [ ] Manually add all users in databricks?
- [ ] Thinking that users should only have read only access

**Comment by yjmrobert** [comment]
What about we host some notebooks in our docs repo and interface with some buttons they can click to import it directly into their shared workspace?

Something like this


![Image](https://user-images.githubusercontent.com/43834308/233370230-ad99d293-2fda-415e-bd4a-103704edf8ae.png)


Which could open a list view similar to our Resources page with little cards of demo notebooks and their description



![Image](https://user-images.githubusercontent.com/43834308/233371126-4c469f57-e798-4dbb-beca-01be5ed8721a.png)


There could be a rendering of the relevant code, or we can jump straight to a "Select Databricks Workspace to Import to" button

**Comment by yjmrobert** [comment]
I'd like to close this as we have a way forward with #734
