### ISSUE TITLE
Document google api access

### ISSUE THREAD

**Issue by ErikApption** [ssc-sp/datahub-portal#693]
We should add to the docs the steps required to access the google API. We figure out how to have the json creds uploaded through the portal in the storage account.

https://github.com/ssc-sp/datahub-docs/blob/main/UserGuide/Databricks/Connecting-Google-API.md

**Comment by davidreneuw** [comment]
I've written my guide into it and changed it up to be more generic for any Google API. @ErikApption please have a look / let me know if you'd want more to be added.

I'll close but feel free to reopen
