### ISSUE TITLE
🧩Demo on Databricks Repos feature

### ISSUE THREAD

**Issue by ErikApption** [ssc-sp/datahub-portal#704]
We had a lot of questions on Git integration and we need a deep dive in the Repos feature from Databricks
https://learn.microsoft.com/en-us/azure/databricks/repos/
Thinking we need the following demos:
- [ ] How to work with .py files instead of a notebook
- [ ] How to use a private git repository
- [ ] How Synchronize files in databricks with the git repository
- [ ] How to use a github repo with py files

**Comment by Sean-Stilwell** [comment]
We have two projects that could be useful to consult for this.
My RADARSAT-1 work: https://github.com/ssc-sp/radarsat1-scripts
Robert Ilyes's project from the fall term: https://github.com/ssc-sp/geospatial-pipeline-eval

**Comment by ErikApption** [comment]
That would be awesome - lets us find a proper home in github for the projects

**Comment by ErikApption** [comment]
> We have two projects that could be useful to consult for this. My RADARSAT-1 work: https://github.com/ssc-sp/radarsat1-scripts Robert Ilyes's project from the fall term: https://github.com/ssc-sp/geospatial-pipeline-eval

lol I did not realize that these were *already* in our github. Thinking these could be broken down into more details:
- [ ] how to connect AWS - this is an important one. Might need more details on how you get the creds on the AWS side.
- [ ] how to use github with Databricks
- [ ] this is a prime demo for VS Code integration as well

**Comment by rfernand387** [comment]
Hi,  Would like to have my team sit in on this DEMO .  Can you send a message to all with a meeting request specific to it please?
