### ISSUE TITLE
Databricks clusters cannot access local file system /tmp

### ISSUE THREAD

**Issue by simon-wang-gc** [ssc-sp/datahub-portal#706]
The following command failed

dbutils.fs.mv("file:/tmp/statements.latest.jsonl", "dbfs:/tmp/statements.latest.jsonl")  

org.apache.spark.api.python.PythonSecurityException: Path 'file:/tmp/statements.latest.jsonl' uses an untrusted filesystem 'com.databricks.backend.daemon.driver.WorkspaceLocalFileSystem', but your administrator has configured Spark to only allow trusted filesystems...

**Comment by simon-wang-gc** [comment]
This is probably not possible: https://learn.microsoft.com/en-gb/azure/databricks/data-governance/credential-passthrough/adls-passthrough#py4jsecuritypy4jsecurityexception--is-not-whitelisted

**Comment by ErikApption** [comment]
> This is probably not possible: https://learn.microsoft.com/en-gb/azure/databricks/data-governance/credential-passthrough/adls-passthrough#py4jsecuritypy4jsecurityexception--is-not-whitelisted

This is odd - they list the tmp file access in this document https://learn.microsoft.com/en-us/azure/databricks/files/

**Comment by simon-wang-gc** [comment]
When pass through is enabled, /tmp becomes an issue. Will continue to investigate if it can be made trusted
