### ISSUE TITLE
Install conda packages in Databricks

### ISSUE THREAD

**Issue by ErikApption** [ssc-sp/datahub-portal#718]
One of our users is looking to install https://anaconda.org/bioconda/hifiasm which is not available in pip. Could we create a small example where we configure packages through conda instead of Pip?

**Comment by ErikApption** [comment]
@Sean-Stilwell  I created this placeholder https://github.com/ssc-sp/datahub-docs/blob/main/UserGuide/Databricks/Conda-Packages.md

**Comment by ErikApption** [comment]
> @ErikApption I think Etienne had David and I look into this last year. %conda is deprecated and they recommend either %pip or using a conda-based docker container (if absolutely necessary): https://docs.databricks.com/libraries/notebooks-python-libraries.html#manage-libraries-with-conda-commands

Oh thank you - and good catch. The docker approach seems a bit heavy weight... another member did suggest the cluster init but wondering if they could install the libs directly from the source github?

**Comment by ErikApption** [comment]
Also noticed that hifiasm is a c++ program - so I'm going to guess that unless it is properly packaged in pip with pre-built binaries, this one might only work with docker? @Sean-Stilwell I'm wondering if there is any way that a user could build the binaries on their box and add them to databricks somehow?

**Comment by ErikApption** [comment]
@Sean-Stilwell another idea - how hard would it be to actually make a pip wheel out of this? The pip wheel package would contain binaries and should be easy to deploy on databricks.

**Comment by Sean-Stilwell** [comment]
@ErikApption  I believe it would be a significant amount of work to make a pip wheel, as I think we would need to create a wrapper for Hifiasm (probably in C or C++) to do that.

I think the Docker solution is probably the best approach, although I don't really have any experience with Docker (that was more Matteo's area of expertise). There are several containers for Hifiasm on Docker Hub that we could potentially try: https://hub.docker.com/search?q=hifiasm

We also got qiime2 working with the cluster shell last year (for Guillaume's work). I don't think it's a good solution for this, but David and I prepared this write-up for Etienne at the time that might be useful: https://github.com/ssc-sp/biodata-pipeline-eval

**Comment by ErikApption** [comment]
so to clarify - the package that they are trying to integrate doesn't even have a python wrapper? In that case, if @simon-wang-gc has some cycles he might be able to look at the effort required to make a docker image but we can prob close this issue and open a new one.

**Comment by Sean-Stilwell** [comment]
As far as I can tell, there is no Python wrapper for Hifiasm.

**Comment by ErikApption** [comment]
Closing this issue as I opened this one instead https://github.com/ssc-sp/datahub-portal/issues/725
