### ISSUE TITLE
Provide a conda based databricks environment

### ISSUE THREAD

**Issue by ErikApption** [ssc-sp/datahub-portal#725]
conda is officially deprecated for databricks but we know there are going to be many packages only available through conda.
Thinking of couple options:

- There seems to be a docker image maintained that has support for conda https://github.com/databricks/containers/tree/master/ubuntu/python-conda
- Otherwise there is Databricks runtime 8.4 ML

The second option seems to be easier to implement. Can we test that one?

**Comment by ErikApption** [comment]
@simon-wang-gc so it looks like 8,4 image is not available anymore but there is a docker image that is available https://hub.docker.com/r/databricksruntime/python-conda

**Comment by simon-wang-gc** [comment]
Looks like 8.4 ML runtine is no longer available at this time (May 8, 2023). Docker using python-conda can still run with 10.4-LTS using "No Isolation Shared" access mode. No credential passthrough is available.

**Comment by yjmrobert** [comment]
closing this as you guys have it handled
