### ISSUE TITLE
Modularize core infrastructure code

### ISSUE THREAD

**Issue by simon-wang-gc** [ssc-sp/datahub-portal#75]
- [x] Restructure the code to modularize each construct in the infrastructure and to be aligned with the project resource provisioning;
- [x] To incorporate the ITSG-38 zoning requirement for Databricks as well as app;
- [x] To reduce the exposure of the service by using private links;
- [x]	To align with responsibility model and permission boundary between the cloud team and the project team;
- [x] To make the code more supportable and sustainable;
- [x] Incorporate with Yannick's environment bootstrap script

**Comment by yjmrobert** [comment]
Going to close this as I think we have it sorted out with them
