### ISSUE TITLE
Collaborator unable to create a PAT

### ISSUE THREAD

**Issue by yjmrobert** [ssc-sp/datahub-portal#751]
### Bug type

Databricks

### What happened?

User is attempting to integrate with third party tools and attempted to create a personal access token
![image](https://user-images.githubusercontent.com/43834308/236507288-b53208ff-cb74-4298-b1a5-ef78744b0bd2.png)

### Expected behavior

User would like to be able to create a PAT

### Reproduction steps

1. Be a collaborator on a workspace with databricks
2. Attempt to create a PAT in databricks

### What browsers are you seeing the problem on?

Chrome

### On what operating system are you experiencing the issue?

Windows

### Code of Conduct

- [X] I agree that none of the information provided is confidential.

**Comment by simon-wang-gc** [comment]
Release 2.2 explicitly gave project_users the ability to create PAT.
