### ISSUE TITLE
Create shortcut for user workspace

### ISSUE THREAD

**Issue by ErikApption** [ssc-sp/datahub-portal#756]
It would be nice to put a link in the emails for opening the workspace. Instead of doing some complex db operations - maybe we could have a link like datahub/w/user-utilisateur that
- if the user has a single workspace - it opens that workspace directly
- if the user has multipel workspaces, we show that list or send the user to their profile

**Comment by yjmrobert** [comment]
possible fix in https://github.com/ssc-sp/datahub-portal/commit/f739e2d54900f5f4684596f23060c30cfd3606e5

**Comment by ErikApption** [comment]
this feature is not required - we already have parameters in the email
