### ISSUE TITLE
Databricks Access French Translation missing

### ISSUE THREAD

**Issue by yjmrobert** [ssc-sp/datahub-portal#769]
### Bug type

DataHub Portal

### What happened?

When viewing the tab it displays empty for the french version. This is likely due to the translation pipeline not firing properly

![image](https://github.com/ssc-sp/datahub-portal/assets/43834308/67e78839-ea15-4fda-88ac-dba4b9db23d3)

### Expected behavior

When I update the english docs it should automatically put a draft in the french version (and log something?)

### Reproduction steps

1. Navigate to file explore
2. Click databricks access
3. Switch to french

### What browsers are you seeing the problem on?

Chrome

### On what operating system are you experiencing the issue?

Windows

### Code of Conduct

- [X] I agree that none of the information provided is confidential.

**Comment by iroelperez** [comment]
Problem solved in Develop. Saving the Databricks.razor file with UTF8 encoding.
